import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Montserrat } from 'next/font/google';

import { QueryProvider } from '@/providers/QueryProvider';
import { ClerkProvider } from '@clerk/nextjs';

import Content from '@/widgets/Content';
import Footer from '@/widgets/Footer';
import Header from '@/widgets/Header';
import Layout from '@/widgets/Layout';

import './globals.scss';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
  weight: ['400', '500', '700']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={`${montserrat.variable}`}>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <QueryProvider>
              <Layout>
                <Header />
                <Content>{children}</Content>
                <Footer />
              </Layout>
            </QueryProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
