import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import { ClerkProvider } from '@clerk/nextjs';

import { AppProviders } from '@/app/providers/AppProviders';
import '@/app/styles/globals.scss';

import Layout from '../src/widgets/Layout';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
  weight: ['400', '500', '700']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={`${montserrat.variable}`}>
          <AppProviders>
            <Layout>{children}</Layout>
          </AppProviders>
        </body>
      </html>
    </ClerkProvider>
  );
}
