import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Montserrat } from 'next/font/google';

import Content from '@/components/Content';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Layout from '@/components/Layout';
import { QueryProvider } from '@/providers/QueryProvider';
import { ClerkProvider } from '@clerk/nextjs';

import './globals.scss';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
  weight: ['400', '500', '700']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ThemeProvider attribute='class' defaultTheme='system'>
        <html lang='en'>
          <body className={`${montserrat.variable}`}>
            <QueryProvider>
              <Layout>
                <Header />
                <Content>{children}</Content>
                <Footer />
              </Layout>
            </QueryProvider>
          </body>
        </html>
      </ThemeProvider>
    </ClerkProvider>
  );
}
